linter:
    rules:
      - avoid_print
      - avoid_unnecessary_containers
      - prefer_final_fields
      - unnecessary_getters_setters
      - unnecessary_new
      - prefer_single_quotes
      - always_use_package_imports
      - prefer_const_constructors
      - avoid_init_to_null
      - prefer_if_null_operators
      - prefer_void_to_null